theme: jekyll-theme-minimal
title: ADA Template Website
description: HELLOOOOOOOOOOOOOO
show_downloads: True
navigation:
  - title: An Evolutionary View on The Making of Good Films 🎬
    url: /
  - title: Example
    url: example
